export const ADD_FAVORITE = "ADD_FAVORITE"
export const REMOVE_FAVORITE = "REMOVE_FAVORITE"
export const TOGGLE_FAVORITE = "TOGGLE_FAVORITE"

export const TOGGLE_GRID = "TOGGLE_GRID"

export const ADD_URL_COMIC = "ADD_URL_COMIC"